repos:
  - repo: local
    hooks:
      - id: templ-generate-repo
        name: templ generate
        entry: templ
        args: [generate]
        language: system
        types: [go]
        pass_filenames: false
        always_run: true
  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: v1.0.0-rc.1
    hooks:
      - id: go-mod-tidy-repo
      - id: go-test-repo-mod
        args: [-race, -count=1]
      - id: go-vet-repo-mod
      - id: go-fumpt-repo
        args: [-l, -w]
      - id: golangci-lint-repo-mod
        args: [--config, .golangci.yaml, --, --fix]
